.sentrio_deployment:
  image: curlimages/curl
  script:
    - |
      if [[ -z "CLIENT_ID" || -z "CLIENT_SECRET" || -z "PROJECT_ID" || -z "APPLICATION_NAME" || -z "APPLICATION_VERSION" || -z "ENVIRONMENT" ]]; then
          echo "FATAL: you must set CLIENT_ID, CLIENT_SECRET, PROJECT_ID, APPLICATION_NAME, APPLICATION_VERSION and ENVIRONMENT variables"
          exit 1
      fi  
    - echo $CI_PROJECT_ID
    - echo $CI_COMMIT_BEFORE_SHA
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_AUTHOR
    - echo $CI_COMMIT_BRANCH
    - |
      if [[ "$CI_COMMIT_BEFORE_SHA" == "0000000000000000000000000000000000000000" ]]
      then
          echo Here
          commits=$(git log --pretty=format:%s --no-merges $CI_COMMIT_SHA..$CI_COMMIT_SHA)
      else
          echo Here2
          commits=$(git log --pretty=format:%s --no-merges $CI_COMMIT_BEFORE_SHA..$CI_COMMIT_SHA)
      fi  
    - echo $commits
    - |
      if [[ -z "$commits" ]]; then
          taskIds=""
      else
          taskIds=$(echo $commits | grep -Eo '[A-Z]+-[0-9]+')
      fi
    - echo $taskIds
    - json="{\"projectId\":\"$PROJECT_ID\",\"release\":{\"application\":\"$APPLICATION_NAME\",https://github.com/sentrio/gitlab-cicdversion\":\"$APPLICATION_VERSION\"},\"tasks\":["
    - |
      oldIFS="$IFS"
      IFS='
      '
      IFS=${IFS:0:1} # this is useful to format your code with tabs
      lines=( $taskIds )
      echo "lines: $lines"
      echo "length: ${#lines[@]}"
      IFS="$oldIFS"  
      for ((i = 0; i < ${#lines[@]}; ++i)); do
        json=$json{\"taskId\":\"${lines[$i]}\",\"taskType\":\"BUG\",\"labels\":[]}
        echo "i plus one: $(($i+1))"
        echo "total: ${#lines[@]}"
        if [[ ${#lines[@]} -gt 1 && $(($i+1)) -lt ${#lines[@]} ]]
        then
          json=$json,
        fi
      done
    - json=$json],\"dateTime\":\"$(date +"%Y-%m-%dT%H:%M:%S%:z")\",\"environment\":\"$ENVIRONMENT\",\"metricSource\":\"AUTOMATION_TOOL\"}
    - echo $json
    - curl -X POST -H 'Content-Type:application/json' -k -v -u $CLIENT_ID:$CLIENT_SECRET 'https://platform.sentrio.io/metrics-ingestor/api/v1/metrics/deployments' -d "$json"