.deploy_to_env:
  image: curlimages/curl
  script:
    - |
      if [[ -z "CLIENT_ID" ||  -z "CLIENT_SECRET" ||  -z "PROJECT_ID" || -z "APPLICATION_NAME" || -z "APPLICATION_VERSION" || -z "ENVIRONMENT" ]]; then
          echo "FATAL: you must set CLIENT_ID, CLIENT_SECRET, PROJECT_ID, APPLICATION_NAME, APPLICATION_VERSION and ENVIRONMENT variables"
          exit 1
      fi  
    - curl -k -U "${CLIENT_ID}:${CLIENT_SECRET}" -X POST 'https://platform.sentrio.io/metrics-ingestor/api/v1/metrics/deployments' -v -d '{"projectId": "${PROJECT_ID}", "release": {"application": "${APPLICATION_NAME}","version" : "${APPLICATION_VERSION}"}, "tasks": [], "dateTime": "2022-09-15T18:57:00+01:00", "environment": "${ENVIRONMENT}", "metricSource": "AUTOMATION_TOOL"}'